---
output: github_document
always_allow_html: yes
---
  
<!-- README.md is generated from README.Rmd. Please edit that file -->  
  
```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, eval = FALSE)

# Read in the trial metadata
trial_metadata <- read.csv(file = "trial_metadata.csv", stringsAsFactors = FALSE, na.strings = c("NA", ""))

# Years and trials
years <- sort(unique(trial_metadata$year))
trials <- sort(unique(trial_metadata$T3_trial_name))

```

# BarleyEnvironmentGWS - Data

Below is information on the data in this subfolder, as well as instructions for obtaining from the [Triticeae Toolbox (T3)](https://triticeaetoolbox.org/barley) the experimental data used in this study. These instructions valid as of `r format(Sys.Date(), "%d %b %Y")`.


## Data in this subfolder

1. `project_entries.xlsx` - metadata for genotypes used in this study, including breeding program name, population group, predigree, family, and other notes.
2. `barley_base_crop_simulation.apsim` - a base APSIM simulation file that is modified to run the crop models described in this analysis.
3. `barley_base_crop_simulation_factorial_cultivars.apsim` - a base APSIM simulation file that is modified to run the comparison of reference cultivars described in this analysis. .
4. `trial_metadata.csv` - metadata for the experimental trials used in this study.



## Data from T3

### Genomewide marker data

The genomewide marker data used in this study are available from T3 and (in a more readily usable form) from the Data Repository for the University of Minnesota using the following persistent link: http://hdl.handle.net/11299/204785.

### Phenotype data

1. Go to https://barley.triticeaetoolbox.org/ and log in.  
2. Under the "Search" tab, go to "Wizard"  
3. In the first "Select Column Type" drop-down, scroll down to "Load trials from experiment:" and select "UMN Spring 2-row MET"  
4. Click "Related Trial Phenotypes" at the bottom of the page and click "Download Phenotypes" to download the data.  
